name: 'HTML Validator'
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: HTML5Validator
      - uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      
        with:
          root: ojeengammah/test.HTML
          blacklist: invalid

      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log    
  outputs:
    result:
    description: 'Successfully passed HTML Valdation'
