name: 'HTML Validator'
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      
      with:
        root: Test_HTML_code
        blacklist: invalid

    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: logFile.txt

    - uses: actions/download-artifact@v3
      with:
        name: log
        path: logtest
